### ISSUE TITLE
Zoom to bbox

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/ram-iD#2]
Zoom to the bbox of the project

**Comment by nbumbarger** [comment]
@olafveerman iD doesn't seem to have a built-in function for centering on a collection of features. The closest thing is a zoomToEntity function, but it's used to keep a single node in view in approximately the same relative position, rather than re-centering on it. Zooming in and out, in general, is handled by incrementing the zoom value- there doesn't seem to be an equivalent to Mapbox's polygon area-aware zooming.

Instead of modifying iD, I'm using a formula to convert a bounding box to the combination of zoom-level and centerpoint used in the iD URL. I've tested it on wide, tall, small and large polygons, in different hemispheres and with different window sizes, and it works pretty well. Using that, we can link to the proper area directly from the front end.
